### ISSUE TITLE
TetGen segfault (memorypool destructor)

### ISSUE THREAD

**Issue by dnkrtz** [inducer/meshpy#21] opened 2016-08-16 14:54 UTC
Getting a segmentation fault in tetrahedralize on this [stanford_bunny.stl](https://github.com/inducer/meshpy/files/420543/bunny.stl.zip). Here's the gdb backtrace:

``
#0  0x00007fffe6548708 in tetgenmesh::memorypool::~memorypool() ()
   from /home/dnkrtz/anaconda3/lib/python3.5/site-packages/meshpy/_tetgen.cpython-35m-x86_64-linux-gnu.so
``

``
#1  0x00007fffe65976a1 in tetgenmesh::freememory() ()
   from /home/dnkrtz/anaconda3/lib/python3.5/site-packages/meshpy/_tetgen.cpython-35m-x86_64-linux-gnu.so
``

``
#2  0x00007fffe659680c in tetrahedralize(tetgenbehavior*, tetgenio*, tetgenio*, tetgenio*, tetgenio*) ()
   from /home/dnkrtz/anaconda3/lib/python3.5/site-packages/meshpy/_tetgen.cpython-35m-x86_64-linux-gnu.so
``

``
#3  0x00007fffe65c0ef8 in (anonymous namespace)::tetrahedralizeWrapper(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*) ()
   from /home/dnkrtz/anaconda3/lib/python3.5/site-packages/meshpy/_tetgen.cpython-35m-x86_64-linux-gnu.so
``

``
#4  0x00007fffe65b93eb in meshpyboost::python::objects::caller_py_function_impl<meshpyboost::python::detail::caller<void (*)(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*), meshpyboost::python::default_call_policies, meshpyboost::mpl::vector5<void, tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*> > >::operator()(_object*, _object*) ()
``

**Comment by inducer** [comment] 2016-08-16 15:17
Can you reproduce this with command line tetgen?

**Comment by dnkrtz** [comment] 2016-08-16 16:05
Command line tetgen returns "Error:  Wrong number of vertices in file bunny.stl", which is thrown when the .stl has a number of vertices that isn't a multiple of 3, since each face is made up of 3 vertices. So I don't think this is a problem on your end (would be nice to get error message instead of segfault though!).

But I don't quite understand the problem - if vertices aren't duplicated, a simple cube .stl could have 8 vertices. Am I missing something?

**Comment by inducer** [comment] 2016-08-16 18:29
If you send me reproducing code, I'll see what I can do about the segfault.

**Comment by dnkrtz** [comment] 2016-08-16 19:52
Saving the .stl in ASCII format fixes the problem, so it seems to be an issue with TetGen's binary .stl parser. In any case, here's some reproducing code, you'll need to pip install trimesh. Thanks!

```
import trimesh
import meshpy.tet

tri_mesh = trimesh.load_mesh('./bunny.stl')
mesh_info = meshpy.tet.MeshInfo()
# Define MeshPy options.
opt = meshpy.tet.Options(switches='pqnn', facesout=True, edgesout=True)
# Generate tetrahedral mesh.
mesh_info.set_points(tri_mesh.vertices)
faces = [list(map(lambda x: int(x), i)) for i in tri_mesh.faces]
mesh_info.set_facets(faces)
mesh_info = meshpy.tet.build(mesh_info, opt)
mesh_info.write_vtk("./test.vtk")
```

**Comment by inducer** [comment] 2016-08-16 21:33
Thanks! Since this seems to be a tetgen issue though, I'll close this for now. In any event, thanks for the report!

**Closed by inducer** 2016-08-16 21:33 UTC
